/// <reference types="astro/client" />
/// <reference path="../worker-configuration.d.ts" />

// worker-configuration.d.ts (generated by `npx wrangler types`, gitignored, rerun
// after changing wrangler.toml bindings) declares `Cloudflare.Env` with D1's `DB`
// binding — this is the type `import { env } from "cloudflare:workers"` resolves
// to (confirmed via `export const env: Cloudflare.Env` in the generated file). The
// rest of our config (Turnstile keys, sender/recipient addresses, IP-hash salt) are
// plain secrets/vars supplied via `.dev.vars` locally or `wrangler pages secret put`
// in production — not Cloudflare "bindings", so `wrangler types` doesn't know about
// them; declared here instead via interface merging (TypeScript merges same-name
// declarations of the `Cloudflare` namespace).
declare global {
  namespace Cloudflare {
    interface Env {
      TURNSTILE_SECRET_KEY: string;
      RESEND_API_KEY: string | undefined;
      CONTACT_FROM_EMAIL: string;
      CONTACT_RECIPIENT_EMAIL: string;
      CONTACT_IP_HASH_SALT: string;
    }
  }
}

export {};
